### ISSUE TITLE
keda依赖是什么？项目里面没有

### ISSUE THREAD

**Issue by jinwufeiyang** [suxiongwei/SpringCloud-Shop#2]
<parent>
		<artifactId>keda</artifactId>
		<groupId>com.kedacom</groupId>
		<version>1.0-SNAPSHOT</version>
	</parent>

**Comment by jinwufeiyang** [comment]
作者没有回复啊，不过这个可以去掉不用好像

**Comment by spland** [comment]
根据pom的依赖提示找到，位于<parent>的artifactId应该要修改为SpringCloud-Shop了，文中作者并未更改，还是沿用的keda
